parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - react-app
  - plugin:@typescript-eslint/recommended
env:
  jest: true
rules:
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
  '@typescript-eslint/indent':
    - off
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/member-delimiter-style':
    - off
  '@typescript-eslint/prefer-interface':
    - off
